/**
 * NexaFreight API — TypeScript types
 *
 * Generated by hand from the backend Pydantic schemas:
 *   src/nexafreight/schemas/auth.py
 *   src/nexafreight/schemas/shipment.py
 *   src/nexafreight/schemas/common.py
 *   src/nexafreight/enums.py
 *
 * DO NOT guess field names. If the backend changes, update here first.
 * Contract drift between these types and the Pydantic models is the #1
 * integration failure mode (per project doc).
 */

// ─── Enums ────────────────────────────────────────────────────────────────────
// Values are StrEnum on the backend — serialised as-is (uppercase strings).

/** src/nexafreight/enums.py :: UserRole */
export type UserRole = 'ADMIN' | 'OPERATOR' | 'VIEWER'

/** src/nexafreight/enums.py :: TransportMode */
export type TransportMode = 'SEA' | 'AIR' | 'ROAD' | 'RAIL'

/** src/nexafreight/enums.py :: ShipmentStatus */
export type ShipmentStatus =
  | 'PLANNED'
  | 'IN_TRANSIT'
  | 'DELIVERED'
  | 'DELAYED'
  | 'CANCELLED'

/** src/nexafreight/enums.py :: LegStatus */
export type LegStatus =
  | 'PLANNED'
  | 'IN_PROGRESS'
  | 'COMPLETED'
  | 'REPLACED'
  | 'CANCELLED'

/** src/nexafreight/enums.py :: Provenance */
export type Provenance =
  | 'REAL'
  | 'REPLAYED'
  | 'DERIVED'
  | 'CALIBRATED'
  | 'SIMULATED'
  | 'MOCK'

/** src/nexafreight/enums.py :: OrderSlaStatus */
export type OrderSlaStatus = 'ON_TIME' | 'AT_RISK' | 'LATE'

// ─── Auth ─────────────────────────────────────────────────────────────────────

/**
 * POST /api/auth/login — request body
 * src/nexafreight/schemas/auth.py :: LoginRequest
 */
export interface LoginRequest {
  email: string
  password: string
}

/**
 * Nested user profile returned inside LoginResponse.
 * src/nexafreight/schemas/auth.py :: UserProfile
 *
 * Note: role is a plain string in this schema (not the UserRole enum),
 * but in practice the backend always sends one of the UserRole values.
 */
export interface UserProfile {
  email: string
  full_name: string
  role: string
  is_active: boolean
}

/**
 * POST /api/auth/login — successful response body
 * src/nexafreight/schemas/auth.py :: LoginResponse
 */
export interface LoginResponse {
  access_token: string
  token_type: string   // always "bearer"
  user: UserProfile
  expires_in: number   // seconds (not minutes)
}

/**
 * GET /api/auth/me — response body
 * src/nexafreight/schemas/auth.py :: UserOut
 *
 * Different shape from UserProfile: adds `id`, drops `is_active`.
 * full_name is nullable here.
 */
export interface User {
  id: number
  email: string
  role: UserRole
  full_name: string | null
}

// ─── Pagination envelope ──────────────────────────────────────────────────────

/**
 * Generic pagination wrapper used by list endpoints.
 * src/nexafreight/schemas/common.py :: PaginatedResponse[T]
 */
export interface PaginatedResponse<T> {
  items: T[]
  total: number        // total matching records across all pages
  page: number         // current page, 1-indexed
  size: number         // items per page
  total_pages: number
}

// ─── Shipments ────────────────────────────────────────────────────────────────

/**
 * One row in GET /api/shipments list.
 * src/nexafreight/schemas/shipment.py :: ShipmentListItem
 *
 * Field names are exact — see Step 2 notes for fields the task doc mentioned
 * that do NOT exist on the backend (reference, dest, provenance).
 */
export interface ShipmentListItem {
  id: string                           // UUID string
  origin: string                       // UN/LOCODE
  destination: string                  // UN/LOCODE — backend field is "destination", not "dest"
  mode: TransportMode
  status: ShipmentStatus
  strictest_sla_deadline: string | null  // ISO-8601 datetime string
  revised_eta: string | null             // ISO-8601 datetime string; ML placeholder for now
}

/**
 * Vessel info nested inside Leg / LegDetail.
 * src/nexafreight/schemas/shipment.py :: VesselInfo
 */
export interface VesselInfo {
  name: string
  mmsi: number
}

/**
 * Route quality classification derived from provenance.
 * src/nexafreight/schemas/shipment.py :: RouteQuality
 *
 * - "high": REAL or CALIBRATED provenance (actual data)
 * - "medium": REPLAYED or DERIVED (historical/computed)
 * - "low": SIMULATED or MOCK (synthetic)
 * - "unknown": other / unrecognized
 */
export type RouteQuality = 'high' | 'medium' | 'low' | 'unknown'

/**
 * Generic GeoJSON geometry object.
 */
export type GeoJSONGeometry = GeoJSON.Geometry

/**
 * One route segment (leg) in a shipment or route plan.
 * Matches backend schemas (LegDetail, RouteFeature) and map routing representations.
 *
 * Fields requested in Phase 2 Step 1:
 *   id, leg_type, sequence, mode, geometry as GeoJSON, route_quality, planned_departure, planned_arrival
 */
export interface Leg {
  id: number | string
  leg_type?: string
  sequence?: number
  sequence_number?: number             // 1-indexed (backend field)
  mode: TransportMode
  status?: LegStatus
  route_version?: number
  origin?: string                      // UN/LOCODE
  destination?: string                 // UN/LOCODE
  geometry?: GeoJSON.Geometry | null
  route_geometry?: GeoJSON.Geometry | null
  route_quality?: RouteQuality
  planned_departure: string            // ISO-8601
  planned_arrival: string              // ISO-8601
  actual_departure?: string | null     // ISO-8601, null if not yet departed
  actual_arrival?: string | null       // ISO-8601, null if not yet arrived
  distance_km?: number | null
  co2_kg?: number | null
  provenance?: Provenance | string
  vessel?: VesselInfo | null
  flight_number?: string | null
}

/**
 * Detailed information about one leg in a shipment's route.
 * src/nexafreight/schemas/shipment.py :: LegDetail
 */
export interface LegDetail extends Leg {
  id: number
  sequence_number: number              // 1-indexed
  status: LegStatus
  route_version: number
  origin: string
  destination: string
  provenance: Provenance
}

/**
 * One order summary nested inside ShipmentDetail.
 * src/nexafreight/schemas/shipment.py :: OrderSummary
 */
export interface OrderSummary {
  id: number
  order_number: string
  sla_deadline: string                 // ISO-8601
  revenue: number                      // USD
  sla_status: OrderSlaStatus
}

/** Alias for OrderSummary */
export type Order = OrderSummary

/**
 * One entry from GET /api/shipments/{id}/events.
 * src/nexafreight/schemas/shipment.py :: ShipmentEvent
 */
export interface ShipmentEvent {
  timestamp: string                    // ISO-8601
  event_type: string
  description: string
  actor: string | null
}

/** Alias for ShipmentEvent */
export type Event = ShipmentEvent

/**
 * Full detail for GET /api/shipments/{id}.
 * src/nexafreight/schemas/shipment.py :: ShipmentDetail
 *
 * Extends ShipmentListItem with route segments (legs), associated orders, and events.
 */
export interface ShipmentDetail extends ShipmentListItem {
  cargo_class?: string
  route_version?: number
  container_count?: number
  legs: Leg[]
  orders: Order[]
  events?: Event[]
}

// ─── GeoJSON & Map ────────────────────────────────────────────────────────────

/**
 * Feature properties for a route segment feature.
 * src/nexafreight/schemas/shipment.py :: RouteFeature
 * src/nexafreight/routers/map.py :: _execute_routes_query
 */
export interface RouteFeatureProperties {
  leg_id?: string
  shipment_id?: string
  mode?: TransportMode | string
  status?: LegStatus | string
  provenance?: Provenance | string
  sequence?: number
  route_quality?: RouteQuality
  [key: string]: unknown
}

/**
 * One GeoJSON Feature in the route FeatureCollection.
 * src/nexafreight/schemas/shipment.py :: RouteFeature
 */
export type RouteFeature = GeoJSON.Feature<GeoJSON.Geometry, RouteFeatureProperties>

/**
 * GeoJSON FeatureCollection for shipment route visualization.
 * src/nexafreight/schemas/shipment.py :: RouteFeatureCollection
 *
 * Returned by GET /api/shipments/{id}/route and GET /api/map/routes.
 * Typed loosely as GeoJSON.FeatureCollection since geometry shapes vary by mode.
 */
export type RouteFeatureCollection = GeoJSON.FeatureCollection

// ─── Ports ────────────────────────────────────────────────────────────────────

/**
 * Port master data and congestion stats.
 * Matches backend models (Port, Location, PortDailyStat) and T-015 port_daily_stats fields.
 * Endpoint: /api/map/ports or database model Port + Location + PortDailyStat
 */
export interface Port {
  id: number | string
  un_locode: string
  locode?: string
  name: string
  lat: number
  lon: number
  latitude?: number
  longitude?: number
  country_code?: string
  congestion_index: number | null
  vessel_count?: number | null
  rolling_90d_avg?: number | null
  provenance?: string
}

/**
 * Properties object for a Port feature inside a GeoJSON FeatureCollection.
 * Returned by GET /api/map/ports.
 */
export interface PortFeatureProperties {
  port_id: string
  location_id?: string | null
  un_locode?: string
  locode?: string
  name: string
  congestion_index: number | null
  provenance?: string
  [key: string]: unknown
}

/**
 * GeoJSON Point feature for port markers on map.
 */
export type PortFeature = GeoJSON.Feature<GeoJSON.Point, PortFeatureProperties>

/**
 * GeoJSON FeatureCollection for port markers and congestion overlay.
 * Returned by GET /api/map/ports.
 */
export type PortFeatureCollection = GeoJSON.FeatureCollection<GeoJSON.Point, PortFeatureProperties>

// ─── Live Positions & Telemetry ───────────────────────────────────────────────

/**
 * Live position report matching T-026 / T-031 / Phase 3 specifications.
 * PositionReport: { asset_type: "VESSEL"|"TRUCK"|"FLIGHT", asset_id, lat, lon, speed_knots, heading_deg, provenance: "REAL"|"REPLAYED"|"SIMULATED", source, timestamp }
 */
export interface PositionReport {
  asset_type: 'VESSEL' | 'TRUCK' | 'FLIGHT' | 'SEA' | 'ROAD' | 'AIR' | string
  asset_id: string
  lat: number
  lon: number
  latitude?: number
  longitude?: number
  speed_knots: number | null
  heading_deg: number | null
  provenance: 'REAL' | 'REPLAYED' | 'SIMULATED' | Provenance | string
  source: string
  timestamp: string
  recorded_at?: string
  reported_at?: string | null
}

/**
 * Backward-compatible alias / canonical map position DTO.
 * src/nexafreight/schemas/map.py :: PositionOut
 */
export interface PositionOut {
  asset_id: string
  asset_type: TransportMode | string   // SEA | ROAD | AIR | RAIL
  latitude: number
  longitude: number
  lat?: number | null
  lon?: number | null
  speed_knots?: number | null
  heading_deg?: number | null
  provenance: Provenance | string
  recorded_at: string                  // ISO-8601
  reported_at?: string | null          // ISO-8601
  source: string
}

/**
 * Per-adapter status object from GET /api/map/feed-health.
 * src/nexafreight/schemas/map.py :: FeedHealthOut
 */
export interface FeedHealth {
  adapter_name: string
  is_healthy: boolean
  last_success_at: string | null       // ISO-8601
  messages_received: number
  provenance: 'REAL' | 'REPLAYED' | 'SIMULATED' | Provenance | string
}

/**
 * Alias for FeedHealth matching backend schema naming.
 */
export type FeedHealthOut = FeedHealth

/**
 * Response for GET /api/map/feed-health.
 * src/nexafreight/schemas/map.py :: FeedHealthResponse
 */
export interface FeedHealthResponse {
  adapters: FeedHealth[]
}


